### ISSUE TITLE
No module named 'undetected_chromedriver'

### ISSUE THREAD

**Issue by grayskripko** [ugorsahin/ChatGPT_Automation#8] opened 2023-05-05 20:46 UTC
```
>>> from chatgpt_automation.chatgpt_client import ChatGPT_Client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/Users/srskr/ChatGPT_Automation/chatgpt_automation/chatgpt_client.py", line 4, in <module>
    import undetected_chromedriver as uc
ModuleNotFoundError: No module named 'undetected_chromedriver'
```
Though I did "pip install ."
Just plain "pip install undetected_chromedriver" solved the problem. It could be specified in setup.py

**Comment by dijikul** [comment] 2023-05-06 23:41
See https://github.com/ugorsahin/ChatGPT_Automation/commit/e44120c4a9687c111de02bfb424309918c5df2a9

Maybe we could bring back the requirements,txt but update to the latest version of `undetected_chromedriver`, which was the cause for https://github.com/ugorsahin/ChatGPT_Automation/issues/3

**Comment by ugorsahin** [comment] 2023-05-07 13:38
It looks like the pyproject.toml file needs the dependencies in a seperate variable instead of in requires section. The problem is fixed now. You can download and install it without any dependency problem. [c8bcf6f](https://github.com/ugorsahin/ChatGPT_Automation/commit/c8bcf6fb9bf1069c0e1e4b079febc7652d234356)

**Closed by ugorsahin** 2023-05-07 13:38 UTC
